language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules
notifications:
  email: false
branches:
  only:
    - master
before_script:
  - npm prune
notifications:
  slack: code4socialgood:63gGHImfymHIsTLbljQ9EFgv
