sudo: required

language: node_js

services:
- docker

branches:
  only:
  - master
  - /^greenkeeper/.*$/

before_install: npm install --global greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script:
- yarn build
- yarn test

after_script: greenkeeper-lockfile-upload

after_success:
- if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./deploy/run.sh ci_deploy_to_test; fi

cache:
  directories:
  - node_modules
  yarn: true

notifications:
  email: false

notifications:
  slack:
    secure: "$SLACK_TOKEN"
