language: node_js
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn build
- yarn test
after_script: greenkeeper-lockfile-upload
cache:
  directories:
  - node_modules
  yarn: true
notifications:
  email: false
branches:
  only:
  - master
  - /^greenkeeper/.*$/
notifications:
  slack:
    secure: "$SLACK_TOKEN"
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app:
    master: calltocode
