language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
  yarn: true
notifications:
  email: false
branches:
  only:
  - master
before_script:
- npm prune
notifications:
  slack: code4socialgood:$SLACK_TOKEN
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "$HEROKU_API_KEY"
  app:
    master: calltocode
