version: '3'

services:
  app:
    image: blueberrymozart/test-c2c
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    ports:
    - 3000:3000
    restart: on-failure
    environment:
    - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    - JWT_SIGNING_KEY=${JWT_SIGNING_KEY}

  db:
    image: mongo:3.4-jessie
    volumes:
    - ../db/seedData:/seedData
    ports:
    - 27017:27017
    - 28017:28017
